name: Publish page to GitHub pages
on: push

jobs:
  build_app:
    name: Build frontend app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build app
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install